### ISSUE TITLE
Compatability with gnome-shell 3.2.0

### ISSUE THREAD

**Issue by rmosse** [kagesenshi/gnome-shell-extensions-pidgin#11]
Broken for gnome 3.2.0 (ubuntu 11.10) error is "TypeError: TelepathyClient.Notification is undefined"

**Comment by matihick** [comment]
is there any quick fix for gnome 3.2?

**Comment by 9er** [comment]
BigE's fork works for me https://github.com/BigE/gnome-shell-extensions-pidgin

**Comment by webexpy** [comment]
I know this has been closed already but I wanted to share, as a quick fix for anyone that might stumble with this, that I've got it working on debian amd64 with gnome-shell 3.2.2.1-2 just by rolling back to the commit immediately before the one for "Update to work with Gnome Shell 3.4".
Kagesenshi I apologise for reopening the thread and as for the rest I hope it helps!!
