### ISSUE TITLE
Doesn't alert when irc chat message contains my nickname

### ISSUE THREAD

**Issue by mpeters** [kagesenshi/gnome-shell-extensions-pidgin#20]
I'm not sure what the problem is as it seems like this should work (and there are some merged commits to this effect - https://github.com/kagesenshi/gnome-shell-extensions-pidgin/commit/18653b62ce27d78e807013b40bea9219e4c6d7bc) but it doesn't.

I'm using Gnome 3.2.1. Private messages in IRC work just fine and I get a popup in the notification and I can respond there just fine. But when someone mentions my name in an irc chatroom it doesn't notify me at all. It's a real pain to have to constantly check that window to make sure I don't have anything I'm missing.

**Comment by kagesenshi** [comment]
it was removed earlier as it was causing problems .. 

I just added a cleaner implementation for chatroom notification + some more improvements .. git pull to get it :-) ..

**Comment by groovenectar** [comment]
FYI for anyone who comes here wondering... You can do this now with the "Message Notification" plugin (at least on Windows)
