### ISSUE TITLE
Gnome 3.4.1

### ISSUE THREAD

**Issue by brendanlong** [kagesenshi/gnome-shell-extensions-pidgin#26]
Any chance you could update this to work on Gnome 3.4.1?

Do they do versioning well enough that you could safely make it work on 3.4.x (or even 3.x.x)?

**Comment by brendanlong** [comment]
Actually, this works just fine in 3.4.1, it just won't let me install it from the extensions site :\

**Comment by kagesenshi** [comment]
ey? ..

i only put 3.4 in the version requirement though .. and afaik if i put 3.4, it will allow 3.4.x just like in 3.2 .. you sure it does not work ?

**Comment by brendanlong** [comment]
Oh, I see. This is just a poor UI on the GNOME Shell extensions page -- it greys out non-compatible extensions, and there's an upgrade button.. but the upgrade button is tiny and also greyed out, so I didn't realize what I was supposed to do.
