### ISSUE TITLE
All Notification Area icons replaced by pidgin icon

### ISSUE THREAD

**Issue by Blind55** [kagesenshi/gnome-shell-extensions-pidgin#4]
When running this extension, all icons in the notification area at the bottom (with the exception of the conversation pictures) are replaced with pidgin icons.

**Comment by bugflux** [comment]
That's not a problem from this extension. It happens to me with dropbox, and others.

**Comment by Skyr** [comment]
afair this is an issue with some versions of the proprietary nvidia driver: https://bbs.archlinux.org/viewtopic.php?id=120918

**Comment by Blind55** [comment]
you are correct. It is an nVidia bug fixed in their latest beta (280.11). Sorry for the noise.
